### ISSUE TITLE
Table 'MySQL.user' doesn't exist

### ISSUE THREAD

**Issue by hadesfeng** [wstart/DB_BaseLine#3]
[20:28:41] [INFO] Connect target success
[20:28:41] [INFO] testing if the target envirment is suitable
[20:28:41] [INFO] target envirment is suitable
[20:28:41] [INFO] testing power baseline
[20:28:41] [ERROR] run mysql  system account can login  
[20:28:41] [INFO] run mysql  account check finish 
Traceback (most recent call last):
  File "db_baseline.py", line 93, in <module>
    result = checkscript.runtest()
  File "/usr/local/soft/DB_BaseLine-master/script/db_baseline_basic.py", line 85, in runtest
    self.run_power_test()
  File "/usr/local/soft/DB_BaseLine-master/script/mysql_baseline.py", line 80, in run_power_test
    result = self.getOneLine(sql)
  File "/usr/local/soft/DB_BaseLine-master/script/mysql_baseline.py", line 473, in getOneLine
    self.cursor.execute(sql)
  File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, u"Table 'MySQL.user' doesn't exist")

**Comment by hadesfeng** [comment]
原因是 Linux默认是区分大小写
        #检查默认管理员账号
        sql = "SELECT * from MySQL.user where user='root';"

不知道作者你当时的环境是不是不区分大小写

**Comment by wstart** [comment]
对 不区分大小写

**Comment by 0neOfU4** [comment]
script/mysql_baseline.py文件的MYSQL全部替换成mysql
