### ISSUE TITLE
[CRITICAL] (1130, u"Host '172.18.16.*' is not allowed to connect to this MySQL server"

### ISSUE THREAD

**Issue by linsihao7788** [wstart/DB_BaseLine#4]
Traceback (most recent call last):
  File "db_bascline.py", line 93, in <module>
    result = checkscript.runtest()
  File "/usr/local/DB_BaseLine-master/script/db_baseline_basic.py", line 91, in runtest
    self.close()
  File "/usr/local/DB_BaseLine-master/script/mysql_baseline.py", line 460, in close
    self.cursor.close()
AttributeError: 'mysql_baseline' object has no attribute 'cursor'
已经在mysql_baseline.py中把127.0.0.1修改成目的机器上面的IP了

**Comment by wstart** [comment]
感谢。

**Comment by linsihao7788** [comment]
> 
> 
> 感谢。

你好，作者。我是在mysql_baseline.py中把127.0.0.1修改成目的机器的IP也还是无法使用到脚本，报错误了，具体的错误是Traceback (most recent call last):
File "db_bascline.py", line 93, in
result = checkscript.runtest()
File "/usr/local/DB_BaseLine-master/script/db_baseline_basic.py", line 91, in runtest
self.close()
File "/usr/local/DB_BaseLine-master/script/mysql_baseline.py", line 460, in close
self.cursor.close()
AttributeError: 'mysql_baseline' object has no attribute 'cursor'
